### ISSUE TITLE
[Linux] No way to return tray icon to classic green icon?

### ISSUE THREAD

**Issue by NintendoManiac64** [element-hq/element-web#28358]
### Steps to reproduce

1. In a live ISO of your favorite Linux distro (I like Mint), download the [official Linux tarball from the official ELement website](https://packages.element.io/desktop/install/linux/index.html)
2. Extract the tarball and launch Element
3. Observe how the tray icon is black & white
4. Right-click on the tray icon
5. Observe how there's no option to revert to the classic green tray icon

I previously had found somewhere on this git various mentions and commits of this black & white tray icon having been added but with a tray context menu to switch to the classic icon, but the commit/pull request adding the black & white icon was supposedly reverted. However, now I can't find *any* mention of this whatsoever?

#### What did you expect?
A way to revert to the classic green tray icon

#### What happened instead?
There's no way to revert to the classic green icon

### Operating system

Linux Mint 21.1

### Application version

1.11.83

### How did you install the app?

official tarball (though this occurs with the flatpak as well)

### Homeserver

N/A as it occurs even without logging in to a given homeserver

### Will you send logs?

Are logs even applicable to this issue...?

**Comment by t3chguy** [comment]
Fixed by https://github.com/element-hq/element-desktop/pull/1934

**Comment by NintendoManiac64** [comment]
Ohhh, I'm on the wrong thing! They're all mentioned in `element-desktop`

So the main thing though is that this issue was introduced by 1.11.82 but, despite the fix having been pulled 2 weeks ago, the newly-released 1.11.83 doesn't include this fix?

This also still doesn't explain why even 1.11.82 lacked the supposed tray context menu option for reverting to the classic green icon...

**Comment by t3chguy** [comment]
1.11.83 was an off cycle release bearing only config changes. The reason the option was missing is only half the feature was merged before someone noticed it broke as soon as you got a notification. Hence the revert.
